spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
    url: jdbc:h2:mem:medtech-application;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
  liquibase:
    enabled: true
    change-log: classpath:/db-migrations/explicit-order.xml


energosbyt:
  rabbit:
    host: 10.5.3.70
    port: 5672
    username: admin
    password: Etooshagh5
    request:
      queue-name: ccb
      timeout-in-ms: 3000