spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/qiwi-energosbyt
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    enabled: true
    change-log: classpath:/db-migrations/explicit-order.xml


energosbyt:
  rabbit:
    request:
      queue-name: queue1
      timeout-in-ms: 30000